export const SPECIALTIES = {
  health: [
    'Nutrition',
    'Fitness',
    'Mental Health',
    'Sleep',
    'Weight Loss',
    'Chronic Illness',
    'Stress Management',
    'Mindfulness',
    'Yoga',
    'Holistic Health',
  ],
  business: [
    'Leadership',
    'Productivity',
    'Entrepreneurship',
    'Career Coaching',
    'Work-Life Balance',
    'Team Building',
    'Executive Coaching',
    'Sales',
    'Marketing',
    'Finance',
  ],
  life: [
    'Personal Development',
    'Relationships',
    'Parenting',
    'Confidence',
    'Goal Setting',
    'Motivation',
    'Time Management',
    'Life Transitions',
    'Happiness',
    'Resilience',
  ],
  male: [
    "Men's Health",
    "Testosterone Optimization",
    "Male Hormone Health",
    "Prostate Health",
    "Male Body Transformation",
    "Male Mental Health"
  ],
  female: [
    "Women's Health",
    "Pre/Postnatal Fitness",
    "Female Hormone Health",
    "PCOS/Endometriosis Support",
    "Menopause Support",
    "Female Body Transformation",
    "Female Mental Health"
  ],
  general: [
    "General Fitness",
    "Muscle Building",
    "Strength Training",
    "Weight Loss",
    "Nutrition",
    "Sports Performance",
    "Injury Rehabilitation",
    "Senior Fitness",
    "Functional Training",
    "Yoga",
    "Pilates",
    "Cardio Conditioning",
    "Endurance Training",
    "Powerlifting",
    "Bodybuilding",
    "CrossFit",
    "Mobility & Flexibility",
    "Mindfulness & Meditation",
    "Life Coaching",
    "Group Fitness",
    "Online/Remote Coaching",
    "Youth Fitness",
    "Athletic Development",
    "Chronic Disease Management",
    "Diabetes Management",
    "Heart Health",
    "Holistic Health",
    "Wellness Coaching",
    "Corporate Wellness",
    "Martial Arts",
    "Boxing/Kickboxing",
    "Swimming",
    "Running/Track",
    "Cycling",
    "Triathlon",
    "Dance Fitness",
    "Adaptive/Disability Fitness",
    "Bloodwork Analysis",
    "Supplementation Protocols",
    "Other (please specify)"
  ]
}; 